language: node_js
node_js:
  - '8'

install:
  - npm install

script:
  - npm test

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "js-rewrite" ]] ; then
    openssl aes-256-cbc -K $encrypted_4dc456b33364_key -iv $encrypted_4dc456b33364_iv
    -in id_rsa.enc -out id_rsa -d
  - git remote add dep ssh://root@kaze.rip:/root/WeebBot-v2/.git
  - git push dep js-rewrite
  - echo "Deployment successful!"