version: "3.5"

services:
    db:
        container_name: weebbot_postgres_container
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: weebbot_dev
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "1231:5432"
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: weebbot_pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "1232:80"
        networks:
            - postgres
        restart: unless-stopped
    elixir:
        # build use a path to a Dockerfile
        build: ./app
        # we set multiple ports as each of our application (but database) will use a different port
        ports:
            - "4000:4000"
        volumes:
            - ".:/app"
            - "/app/deps"
            - "/app/apps/admin/assets/node_modules"
        # the container will not start if the postgres container isn't running
        depends_on:
            - db
        # set up environment variable for the phoenix instance
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PWD}
            POSTGRES_DB_DEV: ${PSQL_DB}
            POSTGRES_HOST: ${PSQL_HOST}

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
